// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fees_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Fee struct {
	T                    int64    `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	V                    float32  `protobuf:"fixed32,2,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fee) Reset()         { *m = Fee{} }
func (m *Fee) String() string { return proto.CompactTextString(m) }
func (*Fee) ProtoMessage()    {}
func (*Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_050e263b2d78d29d, []int{0}
}

func (m *Fee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fee.Unmarshal(m, b)
}
func (m *Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fee.Marshal(b, m, deterministic)
}
func (m *Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fee.Merge(m, src)
}
func (m *Fee) XXX_Size() int {
	return xxx_messageInfo_Fee.Size(m)
}
func (m *Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_Fee proto.InternalMessageInfo

func (m *Fee) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *Fee) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

// GetRequest ...
type GetRequest struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Resolution           int32    `protobuf:"varint,3,opt,name=Resolution,proto3" json:"Resolution,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_050e263b2d78d29d, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *GetRequest) GetResolution() int32 {
	if m != nil {
		return m.Resolution
	}
	return 0
}

// GetResponse ...
type GetResponse struct {
	Fees                 []*Fee   `protobuf:"bytes,1,rep,name=fees,proto3" json:"fees,omitempty"`
	Total                float32  `protobuf:"fixed32,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_050e263b2d78d29d, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetFees() []*Fee {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *GetResponse) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Fee)(nil), "v1.Fee")
	proto.RegisterType((*GetRequest)(nil), "v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "v1.GetResponse")
}

func init() { proto.RegisterFile("fees_service.proto", fileDescriptor_050e263b2d78d29d) }

var fileDescriptor_050e263b2d78d29d = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0x86, 0xe5, 0xf8, 0xeb, 0x57, 0x69, 0x8a, 0x00, 0x8d, 0xba, 0x88, 0x02, 0x42, 0x21, 0xab,
	0x6c, 0x48, 0x94, 0x72, 0x01, 0x56, 0xe9, 0xde, 0x74, 0x8f, 0x0c, 0x0c, 0x25, 0x52, 0x14, 0x87,
	0xcc, 0xd4, 0x07, 0xe0, 0x0a, 0x1c, 0x8d, 0x2b, 0x70, 0x10, 0xe4, 0x98, 0xbf, 0x9d, 0x9f, 0xd1,
	0x3b, 0x7e, 0x5e, 0x1b, 0xf0, 0x89, 0x88, 0xef, 0x98, 0x26, 0xdf, 0x3d, 0x50, 0x35, 0x4e, 0x4e,
	0x1c, 0x26, 0xbe, 0xc9, 0xce, 0xf7, 0xce, 0xed, 0x7b, 0xaa, 0xed, 0xd8, 0xd5, 0x76, 0x18, 0x9c,
	0x58, 0xe9, 0xdc, 0xc0, 0x31, 0x51, 0x5c, 0x82, 0x6e, 0x89, 0xf0, 0x08, 0x94, 0xa4, 0x2a, 0x57,
	0xa5, 0x36, 0x4a, 0x02, 0xf9, 0x34, 0xc9, 0x55, 0x99, 0x18, 0xe5, 0x8b, 0x1d, 0xc0, 0x96, 0xc4,
	0xd0, 0xcb, 0x81, 0x58, 0x70, 0x0d, 0x0b, 0x16, 0x3b, 0x7d, 0xa7, 0x23, 0xe0, 0x29, 0x68, 0x1a,
	0x1e, 0xe7, 0x1d, 0x6d, 0xc2, 0x11, 0x2f, 0x00, 0x0c, 0xb1, 0xeb, 0x0f, 0xc1, 0x96, 0xea, 0x5c,
	0x95, 0x0b, 0xf3, 0x67, 0x52, 0xdc, 0xc0, 0x6a, 0xbe, 0x95, 0x47, 0x37, 0x30, 0xe1, 0x19, 0xfc,
	0x0b, 0xfd, 0x53, 0x95, 0xeb, 0x72, 0xb5, 0x59, 0x56, 0xbe, 0xa9, 0x5a, 0x22, 0x33, 0x0f, 0x83,
	0x53, 0x9c, 0xd8, 0xfe, 0xab, 0x53, 0x84, 0xcd, 0x0e, 0xa0, 0x25, 0xba, 0x8d, 0x0f, 0xc6, 0x16,
	0x96, 0x5b, 0x92, 0x36, 0xc4, 0x8f, 0xc3, 0xf6, 0x6f, 0xe5, 0xec, 0xe4, 0x87, 0xa3, 0xac, 0xc8,
	0x5e, 0xdf, 0x3f, 0xde, 0x92, 0x35, 0x62, 0xed, 0x9b, 0x9a, 0xe4, 0xf9, 0x8a, 0xc5, 0x0a, 0xd7,
	0xc1, 0x75, 0xff, 0x7f, 0xfe, 0x97, 0xeb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x51, 0xe2,
	0x26, 0x4f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FeeServiceClient is the client API for FeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeeServiceClient interface {
	//Get  GetFees
	GetFees(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type feeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeeServiceClient(cc grpc.ClientConnInterface) FeeServiceClient {
	return &feeServiceClient{cc}
}

func (c *feeServiceClient) GetFees(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/v1.FeeService/GetFees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeeServiceServer is the server API for FeeService service.
type FeeServiceServer interface {
	//Get  GetFees
	GetFees(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedFeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFeeServiceServer struct {
}

func (*UnimplementedFeeServiceServer) GetFees(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFees not implemented")
}

func RegisterFeeServiceServer(s *grpc.Server, srv FeeServiceServer) {
	s.RegisterService(&_FeeService_serviceDesc, srv)
}

func _FeeService_GetFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).GetFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FeeService/GetFees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).GetFees(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FeeService",
	HandlerType: (*FeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFees",
			Handler:    _FeeService_GetFees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fees_service.proto",
}
